url = "https://api.open-meteo.com/v1/forecast"

[model]
    [model.best_match]
        model = "best_match"
        name = "Best match"

    [model.dwd_icon_eps_seamless]
        model = "icon_seamless"
        name = "DWD Icon Seamless"

    [model.ifs_025]
        model = "ecmwf_ifs025"
        name = "ECMWF IFS 0.25°"