[ch]
    'CRM' = '06606'
    'MLS' = '06609'
    'PAY' = '06610'
    'CDF' = '06612'
    'FAY' = '06616'
    'FRE' = '06619'
    'SHA' = '06620'
    'GUT' = '06621'
    'HAI' = '06623'
    'HLL' = '06624'
    'GRA' = '06625'
    'GOE' = '06626'
    'PLF' = '06628'
    'MUS' = '06629'
    'BEA' = '06630'
    'BER' = '06631'
    'GRE' = '06632'
    'BUS' = '06633'
    'KOP' = '06635'
    'MUB' = '06636'
    'MER' = '06637'
    'LAG' = '06638'
    'NAP' = '06639'
    'MOE' = '06641'
    'WYN' = '06643'
    'RUE' = '06645'
    'BEZ' = '06646'
    'PSI' = '06647'
    'EGO' = '06648'
    'LUZ' = '06650'
    'SPF' = '06651'
    'ENG' = '06655'
    'GIH' = '06657'
    'PIL' = '06659'
    'SMA' = '06660'
    'REH' = '06664'
    'LEI' = '06666'
    'LAE' = '06669'
    'KLO' = '06670'
    'ALT' = '06672'
    'WAE' = '06673'
    'CHZ' = '06674'
    'EIN' = '06675'
    'AEG' = '06676'
    'BIZ' = '06678'
    'TAE' = '06679'
    'SAE' = '06680'
    'STG' = '06681'
    'ELM' = '06682'
    'SCM' = '06683'
    'GLA' = '06685'
    'QUI' = '06687'
    'CMA' = '06688'
    'HOR' = '06689'
    'ARH' = '06690'
    'EBK' = '06693'
    'GVE' = '06700'
    'DOL' = '06702'
    'BIE' = '06704'
    'CGI' = '06705'
    'COY' = '06710'
    'PUY' = '06711'
    'AIG' = '06712'
    'GSB' = '06717'
    'SIO' = '06720'
    'EVO' = '06722'
    'MVE' = '06724'
    'VIS' = '06727'
    'JUN' = '06730'
    'INT' = '06734'
    'ABO' = '06735'
    'GRH' = '06744'
    'ULR' = '06745'
    'ZER' = '06748'
    'GUE' = '06750'
    'ROE' = '06751'
    'PIO' = '06753'
    'COM' = '06756'
    'CIM' = '06759'
    'OTL' = '06760'
    'MAG' = '06762'
    'LUG' = '06770'
    'STA' = '06771'
    'LUA' = '06775'
    'BUF' = '06778'
    'WFJ' = '06780'
    'DIS' = '06782'
    'SBE' = '06783'
    'DAV' = '06784'
    'CHU' = '06786'
    'AND' = '06787'
    'VIO' = '06788'
    'SRS' = '06790'
    'COV' = '06791'
    'SAM' = '06792'
    'VAB' = '06793'
    'ROB' = '06794'
    'PMA' = '06795'
    'SMM' = '06796'
    'SCU' = '06798'
    'NAS' = '06799'
    'VAD' = '06990'