[t2m]
    name = "Température (2m)"
    unit = "°C"
    granularity = "hourly"
    parameter = "temperature_2m"

[qnh]
    name = "QNH"
    unit = "hPa"
    granularity = "hourly"
    parameter = "pressure_msl"
