name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag meteoch:$(date +%s) -t bigmil/meteoch:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v5
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PW }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: bigmil/meteoch:latest
